POST http://localhost:5000/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username": "zin",
    "email": "zin.it.dev@gmail.com",
    "password": 123
}

###
POST http://localhost:5000/auth/token HTTP/1.1
Content-Type: application/json

{
    "email": "zin.it.dev@gmail.com",
    "password": 123
}